#Draw a black box behind effect icons
effect_box = true
#A list of effects that should not be registered nor shown on JEI
hidden_effects = ["paraglider:exhausted", "alexsmobs:power_down", "alexsmobs:exsanguination", "alexsmobs:debilitating_sting", "alexsmobs:tigers_blessing", "alexsmobs:fear", "alexsmobs:clinging", "alexsmobs:oiled"]
